# Custom Language File for Launcher Customizer

[ejs.app]
title = "DraconiumMC Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR DRACONIUM-MC"

welcomeDescription = "Bienvenue sur DraconiumMC, un univers unique où aventure, puissance et stratégie se rencontrent. Ici, chaque joueur forge sa propre légende dans un monde rempli de défis, de combats épiques et de mystères à découvrir. Que tu choisisses de devenir plus fort, de dominer tes ennemis ou simplement d’explorer, tout est entre tes mains. Rejoins une communauté active, progresse, et écris ton histoire dans un serveur où chaque détail est pensé pour offrir une expérience inoubliable."

welcomeDescCTA = "Tu es à quelques clics de commencer ton aventure."

