# Custom Language File for Launcher Customizer

[ejs.app]
title = "DraconiumMC Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/wZRRnwERSC"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur DraconiumMC"
welcomeDescription = "Notre mission est de vous plonger dans l'univers unique de DraconiumMC, où l'aventure, le PvP et la conquête se rencontrent dans un monde moddé riche en possibilités. Grâce à l'effort collectif de notre communauté, nous avons créé un univers où chaque faction, chaque terrain et chaque bataille a son importance. Le monde que vous allez explorer est vaste et dynamique. Voyagez à travers des terres mystérieuses, affrontez d'autres factions dans des duels intenses, et préparez-vous à devenir le maître de Draconium. Mais n'attendez pas trop longtemps... Les forces du chaos ne cessent de grandir. La guerre approche."
welcomeDescCTA = "Vous êtes à quelques clics seulement de DraconiumMC !"
