[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non essentiel"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "• Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités.."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "SE CONNECTER"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Choisir un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter de nouveaux comptes ou gérer ceux existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur au lancement."
launchDetachedTitle = "Lancer le jeu indépendamment du launcher."
launchDetachedDesc = "Si le jeu n'est pas détaché, fermer le launcher fermera aussi le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Mods ajoutés"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Shaders"
shaderpackDesc = "Activer ou désactiver les shaders. Attention, ils nécessitent une machine puissante."
selectShaderpack = "Choisir un shader"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "Le minimum recommandé est de 3 Go. Mettre min et max identiques peut réduire les lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "Java est vérifié avant le lancement."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options passées à la JVM. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas être inclus."
launcherTabHeaderText = "Paramètres du launcher"
launcherTabHeaderDesc = "Options liées au launcher."
allowPrereleaseTitle = "Autoriser les versions préliminaires."
allowPrereleaseDesc = "Les préversions peuvent contenir des bugs."
dataDirectoryTitle = "Dossier de données"
selectDataDirectory = "Sélectionner le dossier"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu seront stockés ici."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Infos et notes de version."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de version"
changelog = "Changelog"
noReleaseNotes = "Aucune note de version"
viewReleaseNotes = "Voir sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Télécharger et installer les mises à jour."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"

[js.login]
login = "SE CONNECTER"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.landing.launch]
pleaseWait = "Veuillez patienter.."
failureTitle = "Erreur au lancement"
failureText = "Voir la console (CTRL + Shift + i)."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Analyse du système.."
noCompatibleJava = "Aucune version<br>de Java compatible trouvée"
installJavaMessage = "Java {major} 64 bits est requis. Voulez-vous l'installer ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java.."
javaDownloadFailureTitle = "Erreur téléchargement Java"
javaDownloadFailureText = "Voir la console (CTRL + Shift + i)."
javaRequired = "Java est requis<br>pour lancer"
javaRequiredDismiss = "J'ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des infos serveur.."
fatalError = "Erreur fatale"
downloadingFiles = "Téléchargement des fichiers.."
preparingToLaunch = "Préparation du lancement.."
launchingGame = "Lancement du jeu.."
doneEnjoyServer = "Terminé. Amuse-toi bien !"

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
downloadingButton = "Téléchargement.."
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
